name: Cypress Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm i

      - name: Run Cypress tests on ${{ matrix.browser }}
        run: npm run generate:report --browser ${{ matrix.browser }}

      # Upload os resultados de cada browser como um artifact separado
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: allure-results
          retention-days: 10

  generate-report:
    needs: cypress-run
    if: always()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm i

      - name: AWS CLI Setup
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Set timestamp
        id: timestamp
        run: echo "timestamp=$(date --utc +%Y%m%d_%H%M%SZ)" >> "$GITHUB_OUTPUT"

      # Download e mescla os resultados dos diferentes browsers
      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          pattern: allure-results*
          merge-multiple: true
          path: merged-allure-results

      # Baixa o histórico existente do S3
      - name: Download History
        continue-on-error: true  # Caso seja a primeira execução
        run: aws s3 cp s3://allure-history-ad/history/ ./merged-allure-results/history --recursive

      # Gera o relatório Allure
      - name: Generate Allure Report
        run: npx allure generate ./merged-allure-results --clean

      # Atualiza o histórico no S3
      - name: Update History
        run: aws s3 cp ./allure-report/history s3://allure-history-ad/history/ --recursive

      # Faz upload do relatório completo
      - name: Upload Report to S3
        run: |
          aws s3 cp ./allure-report s3://allure-history-ad/report/${{ steps.timestamp.outputs.timestamp }}/ --recursive
          echo "### Test Results - http://allure-history-ad.s3-website.eu-north-1.amazonaws.com/report/${{ steps.timestamp.outputs.timestamp }}/index.html" >> $GITHUB_STEP_SUMMARY