name: Cypress Tests with Allure Report

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: |
          npm ci
          npm install -g allure-commandline

      - name: Run Cypress Tests
        run: npx cypress run
        continue-on-error: true

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 

      - name: Upload Report to S3
        run: |
          aws s3 sync allure-report s3://${{ secrets.AWS_S3_BUCKET }}/reports/${{ github.sha }} --delete
          echo "Report uploaded to https://${{ secrets.AWS_S3_BUCKET }}.s3.amazonaws.com/reports/${{ github.sha }}/index.html"
      
      - name: Log Allure Report Link
        run: |
          REPORT_URL="https://${{ secrets.AWS_S3_BUCKET }}.s3.amazonaws.com/reports/${{ github.sha }}/index.html"
          echo "Allure Report available at: [View Report]($REPORT_URL)"
    

      #- name: Send Allure Report Link to Google Chat
        # env:
         #  WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        # run: |
      #     REPORT_URL="https://${{ secrets.AWS_S3_BUCKET }}.s3.amazonaws.com/reports/${{ github.sha }}/index.html"
          # curl -X POST -H "Content-Type: application/json" \
        #     -d "{\"text\": \"Relatório de testes e2e disponível: $REPORT_URL\"}" \
         #    $WEBHOOK_URL
